site_name: Jongwon Lee's everything
site_url: https://bluefriend.github.io/
repo_url: https://github.com/bluefriend
repo_name: Jongwon Lee's github
strict: true
site_author: Jongwon Lee
theme:
    name: material
    logo: imgs/icon.png
    favicon: imgs/icon.png
    language: en
    font: 
        text: Roboto # Noto Sans # Roboto
        code: Roboto Mono
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.indexes
        - navigation.top
        - navigation.sections
        - navigation.tracking
    icon:
        repo: fontawesome/brands/github
    palette:
        accent: indigo
nav:
    - Profile: index.md
    - Projects:
        - Student:
            - Graduate: projects/graduate.md
            - Embeded firmware: projects/embeded.md
            - Tracker on mobile: projects/tracker.md
        - Teneleven:
            - Google Tango depth filtering: projects/tango.md
            - Virtual city visualize: projects/city_visualize_web.md
        - VIRNECT:
            - CMake: projects/cmake.md
            - CI/CD: projects/cicd.md
            - Unity3D interface: projects/csharp_interface.md
            - Android AAR: projects/android_aar.md
            - iOS: projects/ios_sample.md
            - OpenGL: projects/opengl_sample.md
            - WebAssembly: projects/webassembly.md
    - Blog: blog/graduate.md
    - Photo: photo/index.md
    - Hobby: hobby/index.md
markdown_extensions:
  - attr_list
  - md_in_html
extra:
    alternate:
        - name: 한국어
          link: /
          lang: kr
        - name: English
          link: /en/
          lang: en
extra_css:
  - stylesheets/extra.css
plugins:
  - mkdocs-video:
      is_video: True
        