site_name: Jongwon Lee
site_url: https://bluefriend.github.io/
repo_url: https://github.com/bluefriend
repo_name: Jongwon Lee's github
strict: true
site_author: Jongwon Lee
theme:
    name: material
    logo: imgs/icon.png
    favicon: imgs/icon.png
    language: en
    font: 
        text: Roboto # Noto Sans # Roboto
        code: Roboto Mono
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.indexes
        - navigation.top
        - navigation.sections
        - navigation.tracking
    icon:
        repo: fontawesome/brands/github
    palette:
        accent: indigo
nav:
    - Profile: index.md
    - Student:
        - Graduate: projects/graduate.md
        - Embeded firmware: projects/embeded.md
        - Tracker on mobile: projects/tracker.md
    - Teneleven:
        - Google Tango depth filtering: projects/tango.md
        - Virtual city visualize: projects/city_visualize_web.md
    - VIRNECT:
        - Track:
            - CMake: projects/cmake.md
            - CI/CD: projects/cicd.md
            - Camera module: projects/camera.md
            - WebAssembly: projects/webassembly.md
        - External:
            - Pose estimation: projects/poseestimation.md
            - Floor estimation: projects/depth.md
            - AR with Unity3D: projects/unity_project.md
markdown_extensions:
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
plugins:
  - mkdocs-video:
      is_video: True
        